name: "eccsplorer"
description: "Detection of extrachromosomal circular DNA (eccDNA) from paired-end sequencing data"
keywords:
  - eccdna
  - circular dna
  - extrachromosomal
  - detection
  - paired-end
tools:
  - "eccsplorer":
      description: "Detection of extrachromosomal circular DNA (eccDNA) from paired-end sequencing data"
      homepage: "https://github.com/crimBubble/ECCsplorer"
      documentation: "https://github.com/crimBubble/ECCsplorer"
      tool_dev_url: "https://github.com/crimBubble/ECCsplorer"
      licence: ["MIT"]
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - reads:
        type: file
        description: Input FASTQ files with paired-end reads (R1 and R2 as a list)
        pattern: "*.{fastq,fq,fastq.gz,fq.gz}"
    - fasta:
        type: file
        description: Reference genome in FASTA format
        pattern: "*.{fa,fasta,fa.gz,fasta.gz}"
output:
  - candidates_bed:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_candidates.bed":
          type: file
          description: Candidate eccDNA regions in BED format
          pattern: "*_candidates.bed"
  - junction_reads:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_junction_reads.txt":
          type: file
          description: Junction read information in TXT format
          pattern: "*_junction_reads.txt"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@siyangming"
maintainers:
  - "@siyangming"
