name: genrich
description: Detecting sites of genomic enrichment (peak calling from name-sorted BAM)
keywords:
  - peak_calling
  - enrichment
  - ChIP-seq
  - ATAC-seq
tools:
  - genrich:
      description: Detecting sites of genomic enrichment
      homepage: https://github.com/jsh58/Genrich
      documentation: https://github.com/jsh58/Genrich
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - bam:
      type: file
      description: Name-sorted BAM file
      pattern: "*.bam"
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - bed:
      type: file
      description: BED file containing enrichment sites
      pattern: "*.bed"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@siyangming"
