name: "ecc_finder_map_sr"
description: Detect eccDNA loci from Illumina short reads using mapping mode
keywords:
  - eccDNA
  - short-read
  - Illumina
  - mapping
tools:
  - ecc_finder:
      description: A robust and accurate detection tool to detect eccDNA using Illumina and ONT sequencing
      homepage: https://github.com/njaupan/ecc_finder
      documentation: https://github.com/njaupan/ecc_finder/wiki
      tool_dev_url: https://github.com/njaupan/ecc_finder
      doi: "10.3389/fpls.2021.743742"
      licence: ["GPL-3.0"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - idx:
        type: file
        description: Index file of reference genome for bwa or minimap2
        pattern: "*.{idx,fa,fasta}"
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - query1:
        type: file
        description: Query fastq forward file (uncompressed or bgzipped)
        pattern: "*.{fastq,fq,fastq.gz,fq.gz}"
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - query2:
        type: file
        description: Query fastq reverse file (uncompressed or bgzipped)
        pattern: "*.{fastq,fq,fastq.gz,fq.gz}"
  - - meta4:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. `[ id:'ref' ]`
    - ref:
        type: file
        description: Reference genome fasta file (uncompressed or bgzipped)
        pattern: "*.{fa,fasta,fa.gz,fasta.gz}"

output:
  - csv:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.csv":
          type: file
          description: eccDNA loci in CSV format
          pattern: "*ecc.sr.csv"
  - fasta:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.fasta":
          type: file
          description: eccDNA sequences in FASTA format
          pattern: "*ecc.sr.fasta"
  - versions_ecc_finder:
      - "${task.process}":
          type: string
          description: Process name
      - ecc_finder:
          type: string
          description: Tool name
      - version:
          type: string
          description: Tool version

authors:
  - "@SiYangming"
maintainers:
  - "@SiYangming"