# workflow name
name: ECCFINDER_PIPELINE
# workflow description
description: eccDNA detection using ecc_finder (mapping-based and/or assembly-based)
keywords:
  - eccDNA
  - ecc_finder
  - long-read
  - ONT
  - PacBio
# modules used in this workflow
modules:
  - ecc_finder_map_ont
  - ecc_finder_map_sr
  - ecc_finder_asm_ont
  - ecc_finder_asm_sr
# input definition
input:
  - reads:
      type: channel
      description: |
        Channel containing long reads [val(meta), fastq]
  - genome_fasta:
      type: file
      description: Reference genome fasta file
# output definition
output:
  - eccdna_candidates:
      type: channel
      description: |
        Channel containing eccDNA candidates [val(meta), file]
        CSV from mapping mode, FASTA from assembly mode
  - versions:
      type: channel
      description: Channel containing software versions
authors:
  - "@SiYangming"
maintainers:
  - "@SiYangming"
