name: haarz
description: Split-read detection from segemehl alignment (haarz.x is part of the segemehl package)
keywords:
  - split_read
  - segemehl
  - eccDNA
tools:
  - haarz:
      description: Split-read detection tool (part of segemehl)
      homepage: https://www.bioinf.uni-leipzig.de/Software/segemehl/
      documentation: https://www.bioinf.uni-leipzig.de/Software/segemehl/
      licence: ["GPL-3.0-or-later"]
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - sngl_bed:
      type: file
      description: segemehl .sngl.bed file (split-read candidates)
      pattern: "*.sngl.bed"
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - sr_bed:
      type: file
      description: BED file containing processed split-read regions
      pattern: "*_haarz-SR.bed"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@siyangming"
