{% set name = "fled" %}
{% set version = "1.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  noarch: generic
  script: python -m pip install --no-deps --no-build-isolation .

requirements:
  host:
    - python <3.10
    - pip
  run:
    - python <3.10
    - pysam==0.22
    - networkx==2.5
    - progressbar2
    - biopython==1.76
    - numpy>=1.19.1
    - pyspoa==0.0.6
    - scipy==1.5.3
    - tqdm>=4.51.0
    - minimap2
    - samtools==1.10
    - bedtools
    - seqtk

about:
  home: https://github.com/FuyuLi/FLED
  license: MIT
  summary: 'FLED: a full-length eccDNA detector for long-reads sequencing data'
